Library/Library/Controllers/BookController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Library.Mappers;
using Library.Models;
using Library.Repositories;

namespace Library.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        private readonly IBookRepository _repository;

        public BookController(IBookRepository repo)
        {
            _repository = repo;
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetAllProducts()
        {
            return Json(BookMapper.Map(_repository.GetAll()), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAllReservedBooks()
        {
            return Json(BookMapper.Map(_repository.FindBy(x => x.Reservations.Any(y => y.Return == null && y.User == this.User.Identity.Name))), JsonRequestBehavior.AllowGet);
        }

        public JsonResult Add(Book item)
        {
            _repository.Add(item);
            _repository.Save();
            return Json(item, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Edit(Book product)
        {
            var oldBook = _repository.GetById(product.Id);
            _repository.Edit(oldBook);
            oldBook.Name = product.Name;
            oldBook.Release = product.Release;
            oldBook.Author = product.Author;
            oldBook.Description = product.Description;
            _repository.Save();
            return Json(BookMapper.Map(oldBook), JsonRequestBehavior.AllowGet);
        }

        public JsonResult Delete(Guid id)
        {
            var oldBook = _repository.GetById(id);
            _repository.Delete(oldBook);
            _repository.Save();
            return Json(new { Status = true }, JsonRequestBehavior.AllowGet);
        }

    }
}

Library/Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockout")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Books", "Index", "Book")</li>
                </ul>

                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Log Out", "Logout", "Account")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Library</p>
        </footer>
    </div>

</body>
</html>